// lang.ts

export const translations = {
	en: {
		"view_title": "LaTeX Snippets",
		"search_placeholder": "Search symbol code...",
		"popout_tooltip": "Open in pop-out window",
		"dock_tooltip": "Dock to sidebar",
		"greek_letters": "Greek",
		"operators_and_relations": "Operators & Relations",
		"arrows": "Arrows",
		"delimiters": "Delimiters",
		"maths_constructs": "Maths Constructs",
		"variable_sized_symbols": "Variable-sized Symbols",
		"standard_functions": "Standard Functions",
		"letter_styles": "Letter Styles",
		"misc": "Miscellaneous",
		"edit_symbols_name": "Edit Symbols Configuration",
		"edit_symbols_desc": "Open and edit the symbols.ts file to add custom LaTeX codes and category classifications.",
		"edit_symbols_button": "Open symbols.ts",
		"edit_symbols_error": "Failed to open symbols.ts file. Please open it manually from the plugin folder.",
	},
	zh: {
		"view_title": "LaTeX 片段",
		"search_placeholder": "搜索符号代码...",
		"popout_tooltip": "在浮动窗口中打开",
		"dock_tooltip": "停靠至侧边栏",
		"greek_letters": "希腊字母",
		"operators_and_relations": "运算符与关系",
		"arrows": "箭头",
		"delimiters": "分隔符",
		"maths_constructs": "数学结构",
		"variable_sized_symbols": "可变大小符号",
		"standard_functions": "标准函数",
		"letter_styles": "字母样式",
		"misc": "杂项",
		"edit_symbols_name": "编辑符号配置",
		"edit_symbols_desc": "打开并编辑 symbols.ts 文件以添加自定义 LaTeX 代码和分类。",
		"edit_symbols_button": "打开 symbols.ts",
		"edit_symbols_error": "无法打开 symbols.ts 文件。请从插件文件夹手动打开。",
	}
};